language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: FULL_TEST=1

sudo: required
addons:
  apt:
    sources:
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted universe
    - sourceline: deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe

    packages:
    - mmark
    - xml2rfc

before_install:
- composer update

script:
- if [ "$FULL_TEST" = 1 ]; then composer full-test; else composer test; fi
- make -C docs/RFC
